/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package relacion.proyecto_todo_plus.Interfaz;

import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author 50257
 */
public class PanelGuardar extends javax.swing.JPanel {

    /**
     * Creates new form PanelGuardar
     */
    public PanelGuardar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraProgreso = new javax.swing.JProgressBar();
        btncargar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        btncargar.setBackground(new java.awt.Color(0, 255, 255));
        btncargar.setText("Guardar datos ");
        btncargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargarActionPerformed(evt);
            }
        });

        jLabel1.setText("Guardando...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(484, 484, 484)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(441, 441, 441)
                        .addComponent(btncargar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btncargar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargarActionPerformed
       btncargar.setEnabled(false);
    barraProgreso.setValue(0);
    barraProgreso.setStringPainted(true);

    relacion.proyecto_todo_plus.conexionBD.persistenciaDAO dao =
        new relacion.proyecto_todo_plus.conexionBD.persistenciaDAO();
    relacion.proyecto_todo_plus.arbolBinario.arbolBinario arbol =
        relacion.proyecto_todo_plus.arbolBinario.ArbolCompartido.getArbol();

    final int[] totalNodos = {0};
    contarNodos(arbol.getRaiz(), totalNodos);

    if (totalNodos[0] == 0) {
        javax.swing.JOptionPane.showMessageDialog(null,
            "El árbol está vacío. Cargue datos primero.");
        btncargar.setEnabled(true);
        barraProgreso.setValue(0);
        return;
    }

    javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<Void, Integer>() {

        int procesados = 0;

        @Override
        protected Void doInBackground() throws Exception {
            relacion.proyecto_todo_plus.arbolBinario.producto[] enBD = dao.cargarTodos();
            java.util.Set<Integer> codigosEnBD = new java.util.HashSet<>();
            for (relacion.proyecto_todo_plus.arbolBinario.producto p : enBD) {
                codigosEnBD.add(p.getCodigo());
            }

            sincronizarNodo(arbol.getRaiz(), dao, codigosEnBD, totalNodos[0]);
            return null;
        }

        private void sincronizarNodo(
            relacion.proyecto_todo_plus.arbolBinario.Nodo nodo,
            relacion.proyecto_todo_plus.conexionBD.persistenciaDAO dao,
            java.util.Set<Integer> codigosEnBD,
            int total) throws InterruptedException {

            if (nodo == null) return;

            sincronizarNodo(nodo.getIzq(), dao, codigosEnBD, total);

            relacion.proyecto_todo_plus.arbolBinario.producto p = nodo.getProd();
            if (codigosEnBD.contains(p.getCodigo())) {
                dao.editar(p);   
            } else {
                dao.insertar(p); 
            }

            procesados++;
            int porcentaje = (int) (procesados * 100.0 / total);
            publish(porcentaje);
            Thread.sleep(40); 

            sincronizarNodo(nodo.getDcha(), dao, codigosEnBD, total);
        }

        @Override
        protected void process(java.util.List<Integer> chunks) {
            int valor = chunks.get(chunks.size() - 1);
            barraProgreso.setValue(valor);
        }

        @Override
        protected void done() {
            btncargar.setEnabled(true);
            barraProgreso.setValue(100);
            javax.swing.JOptionPane.showMessageDialog(null,
                "¡Guardado completo! Datos sincronizados en la base de datos.");
        }
    };

    worker.execute();
}

private void contarNodos(relacion.proyecto_todo_plus.arbolBinario.Nodo nodo, int[] contador) {
    if (nodo == null) return;
    contador[0]++;
    contarNodos(nodo.getIzq(), contador);
    contarNodos(nodo.getDcha(), contador);
    }//GEN-LAST:event_btncargarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.JButton btncargar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
