/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package relacion.proyecto_todo_plus.Interfaz;

import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author 50257
 */
public class PanelCarga extends javax.swing.JPanel {

    /**
     * Creates new form PanelCarga
     */
    public PanelCarga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraProgreso2 = new javax.swing.JProgressBar();
        btncargar2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btncargar2.setBackground(new java.awt.Color(0, 255, 255));
        btncargar2.setText("Cargar Datos ");
        btncargar2.setActionCommand("CARGAR DATOS");
        btncargar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargar2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Cargando datos.......");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(barraProgreso2, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(btncargar2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(614, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(btncargar2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(barraProgreso2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncargar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargar2ActionPerformed
          btncargar2.setEnabled(false);
    barraProgreso2.setValue(0);
    barraProgreso2.setStringPainted(true); // muestra el % en la barra

    relacion.proyecto_todo_plus.conexionBD.persistenciaDAO dao =
        new relacion.proyecto_todo_plus.conexionBD.persistenciaDAO();
    relacion.proyecto_todo_plus.arbolBinario.arbolBinario arbol =
        relacion.proyecto_todo_plus.arbolBinario.ArbolCompartido.getArbol();

    javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<Void, Integer>() {

        @Override
        protected Void doInBackground() throws Exception {
            // 1. Traer todos los productos de la BD
            relacion.proyecto_todo_plus.arbolBinario.producto[] productos = dao.cargarTodos();

            if (productos.length == 0) {
                publish(100); // barra llena aunque no haya nada
                return null;
            }

            // 2. Insertar uno por uno en el árbol y publicar progreso
            for (int i = 0; i < productos.length; i++) {
                arbol.insertar(productos[i]);

                // calcula porcentaje real basado en cuántos llevamos
                int porcentaje = (int) ((i + 1) * 100.0 / productos.length);
                publish(porcentaje);

                Thread.sleep(40); // pequeña pausa para que se vea el movimiento
            }
            return null;
        }

        @Override
        protected void process(java.util.List<Integer> chunks) {
            // chunks puede traer varios valores acumulados, tomamos el último
            int valor = chunks.get(chunks.size() - 1);
            barraProgreso2.setValue(valor);
        }

        @Override
        protected void done() {
            btncargar2.setEnabled(true);
            barraProgreso2.setValue(100);
            javax.swing.JOptionPane.showMessageDialog(null,
                "¡Carga completada! Datos en el árbol AVL.");
        }
    };

    worker.execute();
    }//GEN-LAST:event_btncargar2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgreso2;
    private javax.swing.JButton btncargar2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
