/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package relacion.proyecto_todo_plus.Interfaz;

/**
 *
 * @author 50257
 */
public class PanelModificar extends javax.swing.JPanel {

    /**
     * Creates new form PanelModificar
     */
    public PanelModificar() {
        initComponents();
        jButton1.addActionListener(evt -> buscarParaEditar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textField1 = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setText("NOMBRE");

        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Ingrese el nombre del producto para buscar ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "DESCRIPCION", "PRECIO", "COLOR", "CATEGORIA", "MARCA"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("BUSCAR");

        jButton2.setText("EDITAR PRODUCTO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jLabel1)
                                .addGap(48, 48, 48)
                                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(jLabel2)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(430, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Pedir nuevos datos por diálogos simples
    String nombre = textField1.getText().trim();
    if (nombre.isEmpty()) { 
        javax.swing.JOptionPane.showMessageDialog(this, "Primero busque un producto."); 
        return; 
    }
    relacion.proyecto_todo_plus.arbolBinario.arbolBinario arbol =
        relacion.proyecto_todo_plus.arbolBinario.ArbolCompartido.getArbol();
    relacion.proyecto_todo_plus.arbolBinario.producto p =
        arbol.buscaProducto(arbol.getRaiz(), nombre);
    if (p == null) { 
        javax.swing.JOptionPane.showMessageDialog(this, "Producto no encontrado."); 
        return; 
    }

    String nuevoNombre = javax.swing.JOptionPane.showInputDialog(this, "Nuevo nombre:", p.getNombre());
    if (nuevoNombre == null) return;
    String nuevaDesc = javax.swing.JOptionPane.showInputDialog(this, "Nueva descripción:", p.getDescripcion());
    if (nuevaDesc == null) return;
    String precioStr = javax.swing.JOptionPane.showInputDialog(this, "Nuevo precio:", p.getPrecio());
    if (precioStr == null) return;
    String nuevoColor = javax.swing.JOptionPane.showInputDialog(this, "Nuevo color:", p.getColor());
    if (nuevoColor == null) return;
    String nuevaCategoria = javax.swing.JOptionPane.showInputDialog(this, "Nueva categoría:", p.getCategoria());
    if (nuevaCategoria == null) return;
    String nuevaMarca = javax.swing.JOptionPane.showInputDialog(this, "Nueva marca:", p.getMarca());
    if (nuevaMarca == null) return;

    try {
        double nuevoPrecio = Double.parseDouble(precioStr);
        relacion.proyecto_todo_plus.arbolBinario.producto nuevoDato =
            new relacion.proyecto_todo_plus.arbolBinario.producto(
                p.getCodigo(), nuevoNombre, nuevaDesc, nuevoPrecio, nuevoColor, nuevaCategoria, nuevaMarca);

        arbol.editarProducto(p.getCodigo(), nuevoDato);
        new relacion.proyecto_todo_plus.conexionBD.persistenciaDAO().editar(nuevoDato);

        ((javax.swing.table.DefaultTableModel) jTable1.getModel()).setRowCount(0);
        textField1.setText("");
        javax.swing.JOptionPane.showMessageDialog(this, "Producto modificado correctamente.");
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "El precio debe ser un número.");
    }
    }//GEN-LAST:event_jButton2ActionPerformed
    private void buscarParaEditar() {
        String nombre = textField1.getText().trim();
    if (nombre.isEmpty()) { 
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un nombre."); 
        return; 
    }
    relacion.proyecto_todo_plus.arbolBinario.arbolBinario arbol =
        relacion.proyecto_todo_plus.arbolBinario.ArbolCompartido.getArbol();
    relacion.proyecto_todo_plus.arbolBinario.producto p =
        arbol.buscaProducto(arbol.getRaiz(), nombre);

    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    if (p != null) {
        model.addRow(new Object[]{
            p.getCodigo(), p.getNombre(), p.getDescripcion(),
            p.getPrecio(), p.getColor(), p.getCategoria(), p.getMarca()
        });
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Producto no encontrado.");
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
