/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package relacion.proyecto_todo_plus.Interfaz;

import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author 50257
 */
public class PanelCarga extends javax.swing.JPanel {

    /**
     * Creates new form PanelCarga
     */
    public PanelCarga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraProgreso2 = new javax.swing.JProgressBar();
        btncargar2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btncargar2.setBackground(new java.awt.Color(0, 255, 255));
        btncargar2.setText("Cargar Datos ");
        btncargar2.setActionCommand("CARGAR DATOS");
        btncargar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargar2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Cargando datos.......");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(barraProgreso2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btncargar2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(btncargar2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barraProgreso2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncargar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargar2ActionPerformed
        btncargar2.setEnabled(false); // desactiva botón

        SwingWorker<Void, Integer> worker = new SwingWorker<Void, Integer>() {

            @Override
            protected Void doInBackground() throws Exception {

                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(50); // simula proceso
                    publish(i); // envía progreso
                }

                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int valor = chunks.get(chunks.size() - 1);
                barraProgreso2.setValue(valor);
            }

            @Override
            protected void done() {
                btncargar2.setEnabled(true);
                JOptionPane.showMessageDialog(null, "Carga completada");
            }
        };

        worker.execute(); // TODO add your handling code here:
    }//GEN-LAST:event_btncargar2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgreso2;
    private javax.swing.JButton btncargar;
    private javax.swing.JButton btncargar1;
    private javax.swing.JButton btncargar2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
